require:
  - rubocop-rspec
  - rubocop-factory_bot

AllCops:
  Exclude:
    - "db/schema.rb"
    - "bin/*"

  TargetRubyVersion: 3.2.2
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes

Style/Documentation:
  Enabled: false

# Customize rules
Layout/LineLength:
  Max: 95

Metrics/MethodLength:
  Max: 35

Metrics/AbcSize:
   Enabled: false

Metrics/BlockLength:
  Max: 70

RSpec/ExampleLength:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/EmptyExampleGroup:
  Exclude:
    - "spec/requests/**/*"
